package ebank.View;

import ebank.captcha.CaptchaImage;
import java.awt.Color;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author DELL
 */
public class LoginFrame_vi extends javax.swing.JFrame {

    String strVi = "Đăng Nhập";
    String strEn = "Login";
    String NotiCaptcha = "";
    String NotiNCaptcha = "";
    String NotiAcc = "";
    String NotiAcc10 = "";
    String NotiAccNum = "";
    String NotiPass = "";
    String NotiPass8 = "";
    String NotiPassTy = "";
    String NotiNot = "";
    String NotiSus = "";
    /**
     * Creates new form LoginFrame_vi
     */
    String captchaStr;

    public LoginFrame_vi() {
        initComponents();
        setLocationRelativeTo(null);
        reCaptcha();
        ChangeLanguage();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        Name = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnLogin = new javax.swing.JButton();
        Title = new javax.swing.JLabel();
        iconAcc = new javax.swing.JLabel();
        IconPass = new javax.swing.JLabel();
        txtAcc = new javax.swing.JTextField();
        txtCaptcha = new javax.swing.JTextField();
        imageCaptcha = new javax.swing.JLabel();
        txtPass = new javax.swing.JPasswordField();
        Notification = new javax.swing.JLabel();
        iconReload = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255), 2));

        Name.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        Name.setForeground(new java.awt.Color(0, 0, 255));
        Name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Name.setText("EBANK");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Name, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        btnLogin.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnLogin.setText("Đăng nhập");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        Title.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title.setText("Đăng nhập");

        iconAcc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ebank/Icon/user.png"))); // NOI18N

        IconPass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ebank/Icon/padlock.png"))); // NOI18N

        txtAcc.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtAcc.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtAcc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAccActionPerformed(evt);
            }
        });
        txtAcc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtAccKeyReleased(evt);
            }
        });

        txtCaptcha.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtCaptcha.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        imageCaptcha.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtPass.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtPass.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        iconReload.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ebank/Icon/reloadicon.png"))); // NOI18N
        iconReload.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iconReloadMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Notification, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLogin, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Title, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(imageCaptcha, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(iconReload, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(txtCaptcha, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(iconAcc, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IconPass, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtAcc, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                            .addComponent(txtPass))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 21, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(iconAcc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtAcc))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(IconPass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtPass))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtCaptcha, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(iconReload, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(imageCaptcha, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(Notification, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtAccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAccActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAccActionPerformed

    private void iconReloadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconReloadMouseClicked
        // TODO add your handling code here:
        reCaptcha();
    }//GEN-LAST:event_iconReloadMouseClicked

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        //System.out.println("[" + txtAcc.getText() + "]");
        //System.out.println("[" + txtPass.getText() + "]");
        //System.out.println("[" + txtCaptcha.getText() + "]");

        //System.out.println("ebank.View.LoginFrame_vi.btnLoginActionPerformed()");

        //System.out.println("[" + txtAcc.getText().replace(" ", "") + "]");
        //System.out.println("[" + txtPass.getText().replace(" ", "") + "]");
        //System.out.println("[" + txtCaptcha.getText().replace(" ", "") + "]");

        if (txtAcc.getText().isBlank()) {
            Notification.setText(NotiAcc);
            Notification.setForeground(Color.red);
            return;
        }
        if (txtAcc.getText().replace(" ", "").length() != 10) {
            Notification.setText(NotiAcc10);
            Notification.setForeground(Color.red);
            return;
        }
        if (CheckAccNum(txtAcc.getText().replace(" ", ""))!=true) {
            Notification.setText(NotiAccNum);
                Notification.setForeground(Color.red);
                return;
        }
        if (txtPass.getText().isBlank()) {
            Notification.setText(NotiPass);
            Notification.setForeground(Color.red);
            return;
        }
        if (txtPass.getText().replace(" ", "").length() < 8 || txtPass.getText().replace(" ", "").length() > 16) {
            Notification.setText(NotiPass8);
            Notification.setForeground(Color.red);
            return;
        }
        if (CheckPassTy(txtPass.getText())!=true) {
            Notification.setText(NotiPassTy);
            Notification.setForeground(Color.red);
            return;
        }
        if (txtCaptcha.getText().isBlank()) {
            Notification.setText(NotiNCaptcha);
            Notification.setForeground(Color.red);
            return;
        }
        if (!txtCaptcha.getText().equals(captchaStr)) {
            Notification.setText(NotiCaptcha);
            Notification.setForeground(Color.red);
            reCaptcha();
            return;
        }
        Notification.setText(NotiSus);
        Notification.setForeground(Color.GREEN);
        reCaptcha();
        txtCaptcha.setText(null);
    }//GEN-LAST:event_btnLoginActionPerformed

    private boolean CheckAccNum(String a) {
        if (a.isEmpty()) {
            return true;
        }
        for (int i = 0; i < a.length(); i++) {
            int temp = a.charAt(i);
            //System.out.println(temp);
            if (temp > 57 || temp < 48) {
                return false;
            }
        }
        return true;
    }
    private boolean CheckPassTy(String a) {
        if (a.isEmpty()) {
            return true;
        }
        int num=0;
        for (int i = 0; i < a.length(); i++) {
            int temp = a.charAt(i);
            
            if (temp > 57 || temp < 48) {
                num++;
            }
        }
        if (num==a.length()||num==0) {
            return false;
        }
        return true;
    }
    private void txtAccKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAccKeyReleased
        // TODO add your handling code here:
        String TemptxtAcc = txtAcc.getText().replace(" ", "");
        txtAcc.setText(TemptxtAcc);
        if (CheckAccNum(TemptxtAcc) != true) {
            Notification.setText(NotiAccNum);
            Notification.setForeground(Color.red);
            return;
        }
        if (TemptxtAcc.length() > 10) {
            Notification.setText(NotiAcc10);
            Notification.setForeground(Color.red);
            return;
        }
        Notification.setText(null);
    }//GEN-LAST:event_txtAccKeyReleased
    public void reCaptcha() {
        try {
            CaptchaImage obj = new CaptchaImage();
            BufferedImage ima = obj.getCaptchaImage();
            File outputfile = new File("./src/ebank/captcha/image/imagecaptcha.jpg");
            ImageIO.write(ima, "jpg", outputfile);
            captchaStr = obj.getCaptchaString();
            Image bi = ImageIO.read(outputfile);
            imageCaptcha.setIcon(new javax.swing.ImageIcon(bi.getScaledInstance(130, 39, Image.SCALE_SMOOTH)));
        } catch (IOException ex) {
            Logger.getLogger(LoginFrame_vi.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void ChangeLanguage() {
        try {
            File config = new File("./src/ebank/View/Language/config");
            try (Scanner readConfig = new Scanner(config)) {
                String strConfig = readConfig.nextLine();
                System.out.println(strConfig);
                if (strConfig.equals("language : en")) {
                    en_lang();
                } else {
                    vi_lang();
                }
            }
        } catch (Exception e) {
        }
    }

    private void en_lang() {
        Title.setText(strEn);
        btnLogin.setText(strEn);
        NotiCaptcha = "Captcha's not right.";
        NotiNCaptcha = "The Captcha must not be blank.";
        NotiAcc = "The account number must not be blank.";
        NotiPass = "The password must not be blank.";
        NotiNot = "The account or password is incorrect.";
        NotiSus = "Successful login.";
        NotiAcc10 = "The account number must be 10 digits";
        NotiAccNum = "The account number must not contain letters";
        NotiPass8 = "Password must be between 8-16 characters";
        NotiPassTy = "Mật khẩu phải chứa cả chữ và số";
    }

    private void vi_lang() {
        Title.setText(strVi);
        btnLogin.setText(strVi);
        NotiCaptcha = "Captcha không đúng.";
        NotiNCaptcha = "Captcha không được để trống.";
        NotiAcc = "Số tài khoản không được để trống.";
        NotiPass = "Mật khẩu không được để trống.";
        NotiNot = "Tài khoản hoặc mật khẩu không đúng.";
        NotiSus = "Đăng nhập thành công.";
        NotiAcc10 = "Số tài khoản phải 10 chữ số";
        NotiAccNum = "Số tài khoản không được chứa chữ cái";
        NotiPass8 = "Mật khẩu phải trong khoảng 8-16 ký tự";
        NotiPassTy = "Mật khẩu phải chứa cả chữ và số";
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginFrame_vi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new LoginFrame_vi().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IconPass;
    private javax.swing.JLabel Name;
    private javax.swing.JLabel Notification;
    private javax.swing.JLabel Title;
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel iconAcc;
    private javax.swing.JLabel iconReload;
    private javax.swing.JLabel imageCaptcha;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField txtAcc;
    private javax.swing.JTextField txtCaptcha;
    private javax.swing.JPasswordField txtPass;
    // End of variables declaration//GEN-END:variables
}
